/** Verifies evidence: proactive suggestion bubble rendered DOM (#11387) through the package's configured test harness. */
// @vitest-environment jsdom
//
// Evidence generator for #11387: dumps the ACTUAL rendered DOM of the proactive
// suggestion bubble (accept "Do it" + dismiss affordance, data-proactive-
// suggestion) and of a plain assistant reply, so a reviewer can confirm the
// affordance renders without reading the component source. Output lands in
// test-results/evidence/11387-proactive-suggestions/rendered-dom.html.

import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { cleanup, render } from "@testing-library/react";
import type * as React from "react";
import { afterEach, describe, expect, it, vi } from "vitest";
import { __setAppValueForTests } from "../../../state/app-store";
import { AppContext } from "../../../state/useApp";
import type { ShellMessage } from "../shell-state";

vi.mock("@elizaos/ui", () => ({
  Button: (props: Record<string, unknown>) => <button {...props} />,
}));

const clientMock = vi.hoisted(() => ({
  getPermission: vi.fn(() => Promise.resolve({ state: "granted" })),
  getPlugins: vi.fn(() => Promise.resolve([])),
}));
vi.mock("../../../api/client", () => ({ client: clientMock }));

import { __renderThreadLineForParity } from "../ChatOverlay";

function withApp(node: React.ReactElement) {
  const appValue = {
    t: (key: string, vars?: Record<string, unknown>) =>
      String(vars?.defaultValue ?? key),
    loadPlugins: vi.fn(() => Promise.resolve()),
    sendActionMessage: vi.fn(),
    setActionNotice: vi.fn(),
    setTab: vi.fn(),
    handleChatRetry: vi.fn(),
  } as never;
  __setAppValueForTests(appValue);
  return render(
    <AppContext.Provider value={appValue}>{node}</AppContext.Provider>,
  );
}

function makeMessage(overrides: Partial<ShellMessage> = {}): ShellMessage {
  return {
    id: "sg-1",
    role: "assistant",
    content: "Want me to pull your latest balances?",
    createdAt: 0,
    ...overrides,
  };
}

const __dir = dirname(fileURLToPath(import.meta.url));
const EVIDENCE = resolve(
  __dir,
  "../../../../../../test-results/evidence/11387-proactive-suggestions/rendered-dom.html",
);

afterEach(() => {
  cleanup();
  __setAppValueForTests(null);
  vi.clearAllMocks();
});

describe("evidence: proactive suggestion bubble rendered DOM (#11387)", () => {
  it("captures the suggestion + plain reply DOM to the evidence dir", () => {
    const suggestion = withApp(
      __renderThreadLineForParity(
        makeMessage({ source: "proactive-interaction" }),
        { onAcceptSuggestion: vi.fn(), onDismissSuggestion: vi.fn() },
      ),
    );
    const suggestionHtml = suggestion.container.innerHTML;
    cleanup();

    const plain = withApp(
      __renderThreadLineForParity(makeMessage(), {
        onAcceptSuggestion: vi.fn(),
        onDismissSuggestion: vi.fn(),
      }),
    );
    const plainHtml = plain.container.innerHTML;

    expect(suggestionHtml).toContain('data-proactive-suggestion="true"');
    expect(suggestionHtml).toContain("Suggestion");
    expect(suggestionHtml).toContain("Do it");
    expect(plainHtml).not.toContain('data-proactive-suggestion="true"');

    const doc = `<!doctype html>
<meta charset="utf-8">
<title>#11387 proactive suggestion bubble — rendered DOM</title>
<style>body{font:14px system-ui;background:#0d0d0d;color:#eee;padding:24px}h2{color:#ff7a1a}section{border:1px solid #333;border-radius:8px;padding:16px;margin:16px 0}</style>
<h1>#11387 — proactive suggestion bubble rendered DOM</h1>
<p>Generated by ChatOverlay.suggestion.evidence.test.tsx from the real
ThreadLine render path. The suggestion turn (source="proactive-interaction")
carries data-proactive-suggestion="true", the "Suggestion" label, and the
"Do it" / dismiss affordance; a normal assistant reply carries none of them.</p>
<h2>1. Proactive suggestion turn (accept + dismiss affordance)</h2>
<section>${suggestionHtml}</section>
<h2>2. Normal assistant reply (no suggestion affordance)</h2>
<section>${plainHtml}</section>`;

    if (!existsSync(dirname(EVIDENCE))) {
      mkdirSync(dirname(EVIDENCE), { recursive: true });
    }
    writeFileSync(EVIDENCE, doc, "utf8");
  });
});
