// Generated-audio attachment in chat (#8876). The agent can GENERATE audio
// attachments (TTS via @elizaos/plugin-elevenlabs). This drives the in-chat
// preview/play/download journey for such an attachment end-to-end, using REAL
// generated MP3 bytes (produced by a live ElevenLabs round-trip and committed as
// a base64 fixture — see packages/scenario-runner/scripts/real-service-audio-
// roundtrip.mjs and fixtures/real-generated-audio.mp3.b64): open /chat, and
// assert the audio attachment card + native <audio> player render with the
// served bytes as their source (not a download-only fallback). Recordable via
// E2E_RECORD.
import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { expect, type Page, type Route, test } from "@playwright/test";
import {
  installDefaultAppRoutes,
  openAppPath,
  seedAppStorage,
} from "./helpers";

const HERE = path.dirname(fileURLToPath(import.meta.url));
// Real MP3 bytes generated by ElevenLabs TTS ("Real audio generated by elizaOS
// for the attachment pipeline."), stored as base64 to dodge the *.mp3 gitignore.
const MP3_BYTES = Buffer.from(
  readFileSync(
    path.join(HERE, "fixtures", "real-generated-audio.mp3.b64"),
    "utf8",
  ).trim(),
  "base64",
);
// The content-addressed handle of those exact bytes (sha256), matching how
// packages/agent/src/api/media-store.ts derives the served filename.
const HASH = "d49e3d84440aeebaec41766fbeebad2944d178e4a8ead8877375227e3a1ad88a";
const AUDIO_URL = `/api/media/${HASH}.mp3`;
const CONVERSATION_ID = "generated-audio-conversation";
const ROOM_ID = "generated-audio-room";
const NOW = new Date().toISOString();
const NOW_MS = Date.now();

async function installSeededAudioChat(page: Page): Promise<void> {
  const conversation = {
    id: CONVERSATION_ID,
    roomId: ROOM_ID,
    title: "Generated audio chat",
    updatedAt: NOW,
    createdAt: NOW,
  };
  const messages = [
    {
      id: "seed-user-1",
      role: "user" as const,
      text: "Read this back to me as audio.",
      source: "eliza",
      roomId: ROOM_ID,
      timestamp: NOW_MS - 5_000,
    },
    {
      id: "seed-assistant-1",
      role: "assistant" as const,
      text: "Here's the generated audio.",
      source: "eliza",
      roomId: ROOM_ID,
      timestamp: NOW_MS - 2_000,
      attachments: [
        {
          id: "audio-1",
          url: AUDIO_URL,
          contentType: "audio",
          title: "generated-speech.mp3",
          mimeType: "audio/mpeg",
        },
      ],
    },
  ];

  await page.route("**/api/conversations**", async (route) => {
    const url = new URL(route.request().url());
    if (url.pathname !== "/api/conversations") {
      await route.fallback();
      return;
    }
    if (route.request().method() === "GET") {
      await route.fulfill({
        status: 200,
        contentType: "application/json",
        body: JSON.stringify({ conversations: [conversation] }),
      });
      return;
    }
    if (route.request().method() === "POST") {
      await route.fulfill({
        status: 200,
        contentType: "application/json",
        body: JSON.stringify({ conversation }),
      });
      return;
    }
    await route.fallback();
  });

  await page.route(`**/api/conversations/${CONVERSATION_ID}`, async (route) => {
    if (
      route.request().method() === "PATCH" ||
      route.request().method() === "GET"
    ) {
      await route.fulfill({
        status: 200,
        contentType: "application/json",
        body: JSON.stringify({ conversation }),
      });
      return;
    }
    await route.fallback();
  });

  await page.route(
    `**/api/conversations/${CONVERSATION_ID}/messages**`,
    async (route) => {
      if (route.request().method() === "GET") {
        await route.fulfill({
          status: 200,
          contentType: "application/json",
          body: JSON.stringify({ messages }),
        });
        return;
      }
      await route.fallback();
    },
  );

  await page.route(
    `**/api/conversations/${CONVERSATION_ID}/greeting**`,
    async (route) => {
      await route.fulfill({
        status: 200,
        contentType: "application/json",
        body: JSON.stringify({ text: "Ready.", localInference: null }),
      });
    },
  );

  // Serve the REAL generated MP3 bytes for the attachment URL the player loads,
  // with Range support so the native <audio> element can stream/seek.
  await page.route(`**/api/media/${HASH}.mp3`, async (route: Route) => {
    const range = route.request().headers().range;
    if (range) {
      const m = /bytes=(\d+)-(\d*)/.exec(range);
      const start = m ? Number(m[1]) : 0;
      const end = m?.[2] ? Number(m[2]) : MP3_BYTES.length - 1;
      const chunk = MP3_BYTES.subarray(start, end + 1);
      await route.fulfill({
        status: 206,
        headers: {
          "content-type": "audio/mpeg",
          "accept-ranges": "bytes",
          "content-range": `bytes ${start}-${end}/${MP3_BYTES.length}`,
          "content-length": String(chunk.length),
        },
        body: chunk,
      });
      return;
    }
    await route.fulfill({
      status: 200,
      headers: {
        "content-type": "audio/mpeg",
        "accept-ranges": "bytes",
        "content-length": String(MP3_BYTES.length),
      },
      body: MP3_BYTES,
    });
  });
}

test("chat: a generated audio attachment renders an inline player with the served bytes", async ({
  page,
}) => {
  const pageErrors: string[] = [];
  page.on("pageerror", (e) => pageErrors.push(e.message));

  await seedAppStorage(page);
  await installDefaultAppRoutes(page);
  await installSeededAudioChat(page);

  await openAppPath(page, "/chat");

  // Open the chat history sheet so the seeded thread (and its audio card) is
  // actually on-screen — the slim peek sits under the composer otherwise.
  const openSheet = async (): Promise<void> => {
    const grabber = page.getByTestId("chat-sheet-grabber");
    await expect(grabber).toBeVisible({ timeout: 15_000 });
    await grabber.focus();
    await page.keyboard.press("ArrowUp");
    await expect(page.getByTestId("chat-overlay")).toHaveAttribute(
      "data-open",
      "true",
      { timeout: 15_000 },
    );
  };
  await openSheet();

  // The audio attachment card renders (consistent testid with the other tiles).
  const card = page.getByTestId("audio-attachment").first();
  await expect(card).toBeVisible({ timeout: 60_000 });

  // It carries a native <audio> player whose source is the served media URL —
  // i.e. the generated bytes are actually wired in, not a download-only card.
  const player = page.getByTestId("audio-attachment-player").first();
  await expect(player).toBeVisible();
  await expect(player).toHaveJSProperty("tagName", "AUDIO");
  const srcAttr = await player.getAttribute("src");
  expect(srcAttr, "audio src points at the served media URL").toContain(
    `/api/media/${HASH}.mp3`,
  );

  // The browser successfully loads the real MP3: readyState advances past
  // HAVE_NOTHING and a finite duration is decoded from the served bytes.
  await expect
    .poll(
      () =>
        page.evaluate((sel) => {
          const el = document.querySelector(sel) as HTMLAudioElement | null;
          return el ? el.readyState : -1;
        }, '[data-testid="audio-attachment-player"]'),
      { timeout: 30_000 },
    )
    .toBeGreaterThanOrEqual(1); // HAVE_METADATA — the bytes decoded

  // The same generated-audio attachment renders + decodes on a mobile viewport,
  // proving the audio preview works across form factors. (A committed visual of
  // the audio-preview card is covered by the MessageAttachments `Audio` story in
  // the @elizaos/ui story-gate; here we prove the real bytes load and decode.)
  await page.setViewportSize({ width: 390, height: 844 });
  await openSheet();
  await expect(card).toBeVisible();
  await expect(player).toBeVisible();
  await expect
    .poll(
      () =>
        page.evaluate((sel) => {
          const el = document.querySelector(sel) as HTMLAudioElement | null;
          return el ? el.readyState : -1;
        }, '[data-testid="audio-attachment-player"]'),
      { timeout: 15_000 },
    )
    .toBeGreaterThanOrEqual(1);

  expect(pageErrors, "no uncaught page errors").toEqual([]);
});
